import { PublicActions, PublicFooter, PublicHeader } from "@/components/public-layout";
import { ProductIcon } from "@/components/brand";
export default function About() {
  return <><PublicHeader /><main id="main-content" className="public-main"><section className="container about-hero"><p className="eyebrow">ABOUT UPAY FINANCIAL COACH</p><h1>Financial clarity<br /><span>should be easier.</span></h1><p>Everyday money decisions deserve a clear picture. We bring recorded transactions, savings goals, planning and AI-assisted guidance into one approachable experience.</p></section>
    <section className="public-section soft-section"><div className="container feature-split"><div className="section-heading"><p className="eyebrow">OUR PURPOSE</p><h2>More understanding.<br />More informed choices.</h2><p>Help people in Bangladesh understand everyday financial behavior, build purposeful savings habits and make decisions with useful context.</p></div><div className="about-story"><article><span>THE PROBLEM</span><h3>Activity without a clear picture.</h3><p>Income, expenses and goals are often scattered across records. Knowing what happened is only the first step; understanding what it means takes context.</p></article><article><span>OUR APPROACH</span><h3>Connect the records to the decision.</h3><p>Bring financial activity, progress and planning together, then make it easier to ask the right questions in a language that feels familiar.</p></article></div></div></section>
    <section className="public-section container"><div className="section-heading"><p className="eyebrow">WHAT YOU CAN DO</p><h2>A practical toolkit for your financial life.</h2></div><div className="capability-grid">{[["dashboard", "Financial overview", "See recorded cash flow and recent activity at a glance."], ["transactions", "Transaction tracking", "Record and organize everyday income and expenses."], ["goals", "Savings goals", "Track contributions, progress and savings requirements."], ["analytics", "Spending analytics", "Explore categories, trends and illustrative wellness history."], ["coach", "AI coaching", "Discuss your records in English, বাংলা and Banglish."], ["planning", "Planning & affordability", "Explore savings scenarios and assess potential purchases."]].map(([icon, title, text]) => <article className="pillar" key={title}><span className="icon-tile"><ProductIcon name={icon} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="public-section product-section"><div className="container feature-split"><div className="section-heading"><p className="eyebrow">RESPONSIBLE BY DESIGN</p><h2>A helpful coach.<br />You stay in control.</h2><p>AI guidance uses a minimized summary of your recorded finances after authentication. It is contextual and illustrative; it is not a guarantee or professional financial advisory service.</p></div><div className="responsible-panel"><ProductIcon name="coach" /><h3>Guidance, not execution.</h3><p>AI does not move money or execute financial transactions. Review advice against your circumstances and make your own decisions.</p><p>Keep passwords, card details and private identifiers out of conversations. Recorded data can be incomplete, and AI can make mistakes.</p></div></div></section>
    <section className="public-section container feature-split"><div className="section-heading"><p className="eyebrow">PRIVACY & PROTOTYPE SCOPE</p><h2>Be clear about the boundaries.</h2><p>Authentication and record ownership checks protect account access. Your financial views are based on records you enter, not direct access to a verified wallet balance.</p></div><div className="scope-note"><ProductIcon name="shield" /><p>Upay Financial Coach is a prototype project. There is no live Upay wallet connection, official corporate endorsement, regulatory certification claim or guaranteed financial outcome.</p></div></section>
    <section className="container final-cta"><p className="eyebrow">A LITTLE CLARITY GOES A LONG WAY</p><h2>Take the next step<br />with more context.</h2><p>Start with your records. Build a plan that matters to you.</p><PublicActions /></section>
  </main><PublicFooter /></>;
}
