import Link from "next/link";
import { PublicPage } from "@/components/public-page";
import { ProductIcon } from "@/components/brand";
export default function About() {
 return <PublicPage>
  <section data-public-section="hero" className="story-hero container"><div><p className="eyebrow">THE IDEA BEHIND THE WORKSPACE</p><h1>Financial clarity should be easier.</h1><p>Everyday activity becomes more useful when you can understand the story it tells. This prototype brings recorded finances and contextual AI guidance into one experience for users in Bangladesh.</p></div><div className="story-statement"><ProductIcon name="goals" /><span>OUR PURPOSE</span><strong>More understanding.<br />More informed decisions.</strong><p>Built around everyday records and the goals behind them.</p></div></section>
  <section data-public-section="problem" className="public-section soft-section"><div className="container problem-layout"><div className="section-heading"><p className="eyebrow">THE PROBLEM</p><h2>Activity is easy to record.<br />Context can be harder to find.</h2></div><ol className="problem-cards">{["Financial records can be scattered across different places.","Spending patterns are difficult to see one entry at a time.","Savings often need a target, a timeline and a repeatable routine.","A purchase price alone does not explain affordability.","Financial information needs context to become useful."].map(text => <li key={text}><ProductIcon name="analytics" />{text}</li>)}</ol></div></section>
  <section data-public-section="approach" className="public-section container"><div className="section-heading"><p className="eyebrow">OUR APPROACH</p><h2>A decision loop, not another pile of numbers.</h2></div><div className="decision-loop">{[["Record","Bring income and expenses into your workspace."],["Understand","Explore cash flow, categories and progress."],["Plan","Connect savings targets with practical scenarios."],["Improve","Review your records as circumstances change."]].map(([title,text],index) => <article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section data-public-section="why-ai" className="public-section ai-section"><div className="container feature-split"><div className="section-heading"><p className="eyebrow">WHY AI BELONGS HERE</p><h2>Ask a question.<br />Understand the context.</h2><p>Conversational guidance can help interpret your recorded financial picture in English, বাংলা or Banglish. You can ask follow-up questions instead of interpreting every number alone.</p></div><div className="responsible-panel"><div className="language-tags"><span>English</span><span lang="bn">বাংলা</span><span>Banglish</span></div><ProductIcon name="coach" /><h3>AI supports your decisions.</h3><p>It does not decide for you, move money or guarantee outcomes. Review its illustrative guidance against your circumstances.</p></div></div></section>
  <section data-public-section="ecosystem" className="public-section container"><div className="section-heading"><p className="eyebrow">THE PRODUCT ECOSYSTEM</p><h2>One set of records. Connected ways to understand it.</h2></div><div className="ecosystem" aria-label="Recorded transactions inform the dashboard, analytics, goals, planning and AI Coach"><div className="ecosystem-source"><ProductIcon name="transactions" /><strong>Recorded transactions</strong><span>Income + expenses</span></div><div className="ecosystem-path"><ProductIcon name="arrow" /><span>Your financial context</span></div><div className="ecosystem-tools">{["Dashboard","Analytics","Savings goals","Planning","AI Coach"].map(label => <span key={label}>{label}</span>)}</div></div><p className="muted">Conceptual product map. Each tool uses the existing recorded context relevant to its purpose; goal contributions remain explicitly recorded.</p></section>
  <section data-public-section="responsibility" className="public-section soft-section"><div className="container feature-split"><div className="section-heading"><p className="eyebrow">RESPONSIBLE BY DESIGN</p><h2>You keep the control.</h2><p>You record your information and choose how to use the tools. Data can be incomplete, and AI can make mistakes.</p></div><ul className="responsibility-list"><li>User-recorded financial information</li><li>Illustrative AI guidance</li><li>No execution of financial transactions</li><li>There is no live Upay wallet connection</li></ul></div></section>
  <section data-public-section="vision" className="public-section container vision-section"><p className="eyebrow">WHAT THE PROTOTYPE DEMONSTRATES</p><h2>Financial understanding could be part of everyday digital life.</h2><p>This hackathon project explores how an AI-assisted financial workspace could complement a digital financial experience. It is not an official production Upay application or professional financial advisory service.</p><Link className="button" href="/features">Explore what the product can do <ProductIcon name="arrow" /></Link></section>
 </PublicPage>;
}
