import Link from "next/link";
import { PublicActions } from "@/components/public-layout";
import { PublicPage, FinalCta } from "@/components/public-page";
import { ProductPreview } from "@/components/product-preview";
import { HeroVisual } from "@/components/hero-visual";
import { ProductIcon } from "@/components/brand";
import { ChatPreview, GoalPreview, PlanningPreview } from "@/components/public-previews";
export default function Home() {
  return <PublicPage>
    <section data-public-section="hero" className="home-hero"><div className="container landing-hero"><div className="hero-copy"><p className="eyebrow">EVERYDAY MONEY. A SMARTER PERSPECTIVE.</p><h1>Smarter money.<br />Better decisions.<br /><span>Powered by AI.</span></h1><p className="hero-description">Record financial activity, understand spending, build savings goals and explore decisions with an AI coach that speaks your language.</p><PublicActions explore /><small className="hero-footnote">Financial coaching prototype · Recorded data, no live wallet connection.</small></div><HeroVisual /></div></section>
    <section data-public-section="capability-stats" className="capability-strip container" aria-label="Product capabilities">{[["8","Core capabilities","From transactions to planning"],["3","Language modes","English · বাংলা · Banglish"],["2","Planning tools","Savings simulator + affordability"],["1","Financial workspace","Your recorded finances, together"]].map(([number,title,text]) => <div key={title}><strong>{number}</strong><div><h2>{title}</h2><p>{text}</p></div></div>)}</section>
    <section data-public-section="capabilities" className="public-section container"><div className="section-heading"><p className="eyebrow">A CONNECTED FINANCIAL TOOLKIT</p><h2>Useful tools for real everyday questions.</h2></div><div className="capability-grid">{[["dashboard","Financial dashboard","Scan recorded balance, income, expenses, goal savings and cash flow."],["transactions","Transaction tracking","Add, edit, delete, search and filter your recorded financial activity."],["goals","Savings goals","Track targets, dates, contributions, progress and pause/resume status."],["analytics","Financial analytics","Explore spending categories, monthly patterns and saved wellness history."],["coach","AI financial coach","Discuss your recorded context in English, বাংলা or Latin-script Banglish."],["planning","Planning & affordability","Test a savings scenario or assess a purchase before making a decision."]].map(([icon,title,text]) => <article className="feature-card" key={title}><span className="icon-tile"><ProductIcon name={icon} /></span><h3>{title}</h3><p>{text}</p></article>)}</div><Link className="inline-link section-space" href="/features">Explore all features <ProductIcon name="arrow" /></Link></section>
    <section data-public-section="dashboard" className="public-section soft-section"><div className="container feature-split"><ProductPreview /><div className="section-heading"><p className="eyebrow">THE PICTURE BEHIND YOUR RECORDS</p><h2>See your financial life in one place.</h2><p>A recorded balance is only the beginning. Bring monthly cash flow, spending categories, savings progress and illustrative wellness into the same workspace.</p><ul className="feature-list"><li><ProductIcon name="dashboard" />Income, expenses and goal savings</li><li><ProductIcon name="analytics" />Cash-flow patterns and wellness assessments</li><li><ProductIcon name="goals" />Targets, contributions and remaining amounts</li></ul><small className="muted">Preview values are illustrative, never your account data.</small></div></div></section>
    <section data-public-section="workflow" className="public-section container"><div className="section-heading"><p className="eyebrow">FROM ACTIVITY TO UNDERSTANDING</p><h2>A practical routine you can repeat.</h2></div><div className="home-process">{["Record","Understand","Set goals","Plan","Ask AI","Improve"].map((title,index) => <div key={title}><span>0{index+1}</span><strong>{title}</strong><ProductIcon name="arrow" /></div>)}</div><Link className="inline-link section-space" href="/how-it-works">See the complete process <ProductIcon name="arrow" /></Link></section>
    <section data-public-section="ai" className="public-section ai-section"><div className="container feature-split"><div className="section-heading"><p className="eyebrow">YOUR AI FINANCIAL COACH</p><h2>A useful conversation.<br />In your own language.</h2><p>Ask about your recorded spending, savings or goals. AI helps interpret your financial context and offers illustrative guidance; you remain in control.</p><div className="language-tags"><span>English</span><span lang="bn">বাংলা</span><span>Banglish</span></div><Link className="button brand-cta" href="/features#ai-coach">Explore AI Coach <ProductIcon name="arrow" /></Link></div><ChatPreview /></div></section>
    <section data-public-section="planning" className="public-section container"><div className="section-heading"><p className="eyebrow">GOAL → PLAN → DECISION</p><h2>Give your next decision a little more context.</h2><p>Set a savings target, explore a monthly scenario, then assess a purchase against recorded cash flow, selected goal reserves and an emergency buffer.</p></div><div className="planning-triptych"><GoalPreview /><PlanningPreview /><PlanningPreview affordability /></div></section>
    <section data-public-section="trust"><div className="container trust-ribbon"><div><ProductIcon name="shield" /><strong>Authenticated access</strong></div><div><ProductIcon name="profile" /><strong>User-isolated records</strong></div><div><ProductIcon name="transactions" /><strong>No live wallet connection</strong></div><Link href="/security">Understand the boundaries</Link></div><FinalCta /></section>
  </PublicPage>;
}
