import Link from "next/link";
import { PublicActions, PublicFooter, PublicHeader } from "@/components/public-layout";
import { ProductPreview } from "@/components/product-preview";
import { ProductIcon } from "@/components/brand";
const pillars = [
  ["transactions", "Understand your money", "Bring recorded income, expenses and spending patterns into a clearer picture."],
  ["goals", "Build your savings", "Give your savings a purpose, track contributions and see your progress."],
  ["planning", "Plan before spending", "Explore a savings scenario or assess a purchase before making your next move."],
  ["coach", "Ask your financial coach", "Talk through your recorded finances in English, বাংলা or Banglish."],
];
export default function Home() {
  return <><PublicHeader /><main id="main-content" className="public-main">
    <section className="container landing-hero"><div className="hero-copy"><p className="eyebrow"><span /> SMARTER MONEY DECISIONS</p><h1>Understand your money.<br /><span>Plan your next move.</span></h1><p className="hero-description">Turn everyday financial records into a clearer path forward. Track your spending, build savings goals and explore decisions with an AI-assisted coach.</p><PublicActions /><p className="hero-footnote"><ProductIcon name="shield" /> Your records. Your goals. Your private account.</p><small className="muted">Prototype · No live Upay wallet connection.</small></div><div className="hero-product"><ProductPreview /><div className="preview-decoration" aria-hidden="true" /></div></section>
    <section id="features" className="public-section soft-section"><div className="container"><div className="section-heading"><p className="eyebrow">A CLEARER FINANCIAL PICTURE</p><h2>One place to understand<br />your financial life.</h2><p>Less guesswork. More context for the choices that matter.</p></div><div className="pillar-grid">{pillars.map(([icon, title, text]) => <article className="pillar" key={title}><span className="icon-tile"><ProductIcon name={icon} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section id="how-it-works" className="public-section container"><div className="section-heading"><p className="eyebrow">FROM RECORDS TO DIRECTION</p><h2>A simple rhythm for better habits.</h2><p>Start with what you know. Build clarity as you go.</p></div><div className="steps-grid">{[["Record", "Add your income, expenses and everyday financial activity."], ["Understand", "See your cash flow, spending categories and illustrative wellness."], ["Plan", "Set a savings goal and explore scenarios before committing."], ["Improve", "Use contextual coaching to think through your next decision."]].map(([title, text], index) => <article key={title}><span className="step-number">0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="public-section product-section"><div className="container"><div className="section-heading"><p className="eyebrow">BUILT FOR EVERYDAY MONEY</p><h2>The tools you need.<br />The context you were missing.</h2><p>One connected experience, from a recorded transaction to a considered plan.</p></div><div className="experience-grid"><article className="experience-card"><ProductIcon name="dashboard" /><h3>Your financial dashboard</h3><p>A useful overview of recorded cash flow, goal savings and recent activity.</p><div className="mini-metrics"><div><small>Income</small><strong>BDT 50,000</strong></div><div><small>Expenses</small><strong>BDT 35,000</strong></div></div><small className="demo-label">Illustrative demo values</small></article><article className="experience-card"><ProductIcon name="goals" /><h3>Progress with a purpose</h3><p>Keep contributions, targets and monthly savings requirements in view.</p><div className="mini-goal"><span>Emergency fund</span><strong>25%</strong><progress value={25} max={100} aria-label="Illustrative savings progress" /></div><small className="demo-label">Illustrative demo goal</small></article><article className="experience-card"><ProductIcon name="analytics" /><h3>A closer look at spending</h3><p>Understand categories, monthly trends and your recorded financial wellness.</p><div className="mini-chart" aria-label="Illustrative category chart"><i style={{ height: "55%" }} /><i style={{ height: "85%" }} /><i style={{ height: "42%" }} /><i style={{ height: "68%" }} /><i style={{ height: "32%" }} /></div><small className="demo-label">Illustrative chart · not account data</small></article></div></div></section>
    <section className="public-section container feature-split"><div className="section-heading"><p className="eyebrow">A COACH THAT SPEAKS YOUR LANGUAGE</p><h2>Good questions.<br />More informed decisions.</h2><p>After you sign in, your coach uses recorded financial context to help you think through spending and savings. Choose the language that feels natural.</p><div className="language-tags"><span>English</span><span lang="bn">বাংলা</span><span>Banglish</span></div><p className="responsibility-note">Guidance is contextual and illustrative, not guaranteed professional financial advice. AI never executes a financial transaction.</p><Link className="inline-link" href="/about">Our responsible AI approach <ProductIcon name="arrow" /></Link></div><div className="demo-chat"><div className="preview-top"><span><ProductIcon name="coach" /> Financial coach</span><span className="demo-label">Static example</span></div><div className="demo-chat-user">How can I start building an emergency fund?</div><div className="demo-chat-answer"><span className="coach-avatar" aria-hidden="true">u</span><p>Start with a target that fits your needs. Review your recorded income and essential spending, then choose a monthly contribution you can maintain.</p></div><div className="demo-composer">A little guidance for your next move.<ProductIcon name="arrow" /></div></div></section>
    <section className="public-section soft-section"><div className="container feature-split"><div className="planning-demo"><p className="eyebrow">EXPLORE BEFORE YOU COMMIT</p><h3>A scenario, not a commitment.</h3><div className="scenario-line"><span>Monthly saving</span><strong>BDT 5,000</strong></div><div className="scenario-line"><span>Time horizon</span><strong>12 months</strong></div><div className="scenario-total"><small>Projected savings</small><strong>BDT 60,000</strong></div><small className="muted">Illustrative scenario. No records or wallet funds are changed.</small></div><div className="section-heading"><p className="eyebrow">MAKE ROOM FOR WHAT MATTERS</p><h2>Plan with a clearer<br />view of the trade-offs.</h2><p>Explore what-if savings, affordability and spending patterns. Understand how your recorded cash flow relates to your goals before deciding what comes next.</p><ul className="feature-list"><li><ProductIcon name="goals" /> Savings goals and contribution tracking</li><li><ProductIcon name="planning" /> What-if scenarios and purchase assessments</li><li><ProductIcon name="analytics" /> Recorded spending and monthly trends</li></ul></div></div></section>
    <section id="security" className="public-section container"><div className="section-heading"><p className="eyebrow">CLARITY INCLUDES KNOWING THE LIMITS</p><h2>Your account. Your financial records.</h2><p>Trust begins with being clear about what this prototype does—and what it does not.</p></div><div className="trust-grid">{[["Secure authentication", "Sign in through Supabase authentication to access your account."], ["User-isolated records", "Protected APIs check record ownership before reading or changing data."], ["Recorded-data insights", "Calculations use your recorded activity, not a verified wallet balance."]].map(([title, text]) => <article key={title}><ProductIcon name="shield" /><h3>{title}</h3><p>{text}</p></article>)}</div><div className="scope-note"><ProductIcon name="shield" /><p>This is an AI-assisted financial coaching prototype. It does not connect to a live Upay wallet and does not imply an official Upay partnership or endorsement.</p></div></section>
    <section className="container final-cta"><p className="eyebrow">YOUR NEXT STEP STARTS WITH CLARITY</p><h2>Build better financial habits,<br />one decision at a time.</h2><p>Bring your records together. Give your savings a direction.</p><PublicActions dashboardLabel="Open dashboard" signupLabel="Create an account" /></section>
  </main><PublicFooter /></>;
}
