"use client";
import { useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { useAction, useResource } from "@/lib/frontend/hooks";
import { queryPath } from "@/lib/frontend/api-client";
import type { Health, Spending } from "@/lib/frontend/types";
import { Empty, Field, Limitations, Metric, Notice, PageTitle, Pagination, ResourceState, SpendingBars, currentDate, date, money } from "@/components/ui";
export default function AnalyticsPage() {
  const { request } = useAuth(), action = useAction();
  const [filters, setFilters] = useState<Record<string, string>>({}), [historyPage, setHistoryPage] = useState(1);
  const spending = useResource<Spending>(queryPath("/analytics/spending", filters)), health = useResource<Health>("/financial-health");
  const history = useResource<Health[]>(`/financial-health?mode=history&page=${historyPage}&pageSize=10`);
  const data = spending.data;
  return <><PageTitle title="Analytics" description="Understand your recorded spending and illustrative financial wellness." />
    <section className="card"><form className="filters" onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); setFilters(Object.fromEntries([...fields.entries()].filter(([, value]) => String(value)).map(([key, value]) => [key, String(value)]))); }}><Field label="Start date"><input name="startDate" type="date" max={currentDate()} /></Field><Field label="End date"><input name="endDate" type="date" max={currentDate()} /></Field><button className="secondary" type="submit">Apply period</button><button type="button" disabled={action.busy || spending.loading || Boolean(spending.error)} onClick={() => action.run(async () => { await request("/analytics/refresh", { method: "POST", body: filters }); spending.reload(); }, "Spending insight saved to your dashboard.")}>Refresh & save insight</button></form><p className="muted">Default: past 90 days. Custom ranges may contain up to 366 days.</p><Notice error={action.error} success={action.success} /><ResourceState {...spending} /></section>
    {data && <><p className="muted section-space">{date(data.period.startDate)} – {date(data.period.endDate)} · Asia/Dhaka · {data.transactionCount} transactions</p><div className="grid three"><Metric label="Recorded income" value={money(data.totalIncome)} /><Metric label="Recorded expenses" value={money(data.totalExpenses)} /><Metric label="Net cash flow" value={money(data.netCashFlow)} /></div>
      <div className="grid two section-space"><section className="card"><h2>Category spending</h2><SpendingBars data={data} /></section><section className="card"><h2>Monthly trends</h2>{data.transactionCount === 0 && <Empty>No recorded transactions in this period.</Empty>}<div className="table-wrap"><table><thead><tr><th>Month</th><th>Income</th><th>Expenses</th><th>Net</th></tr></thead><tbody>{data.spendingTrends.map(item => <tr key={item.month}><td>{item.month}</td><td>{money(item.totalIncome)}</td><td>{money(item.totalExpenses)}</td><td>{money(item.netCashFlow)}</td></tr>)}</tbody></table></div><p className="muted">Compared with the previous equal-length period: income {data.comparison.incomeChangePercent === null ? "not comparable" : `${data.comparison.incomeChangePercent}%`}, expenses {data.comparison.expenseChangePercent === null ? "not comparable" : `${data.comparison.expenseChangePercent}%`}.</p></section></div></>}
    <section className="card section-space"><div className="row"><h2>Illustrative financial wellness</h2><button className="secondary" disabled={action.busy} onClick={() => action.run(async () => { await request("/financial-health/refresh", { method: "POST", body: { lookbackMonths: 3, store: true } }); health.reload(); history.reload(); }, "Wellness assessment saved.")}>Save assessment</button></div><ResourceState {...health} />{health.data && <><p><strong>{health.data.healthScore}/100</strong> overall · {date(health.data.assessmentDate)}</p>{([ ["Savings", health.data.savingsScore], ["Spending", health.data.spendingScore], ["Goals", health.data.goalScore], ["Emergency", health.data.emergencyScore] ] as [string, number][]).map(([label, score]) => <div className="score-row" key={label}><span>{label}</span><progress value={score} max={100} aria-label={`${label} score`} /><strong>{score}</strong></div>)}<Limitations items={health.data.limitations} /></>}</section>
    <section className="card section-space"><h2>Wellness history</h2><ResourceState {...history} />{history.data?.length === 0 && <Empty>Save an assessment to start your history.</Empty>}{history.data && history.data.length > 0 && <div className="table-wrap"><table><thead><tr><th>Date</th><th>Overall</th><th>Savings</th><th>Spending</th><th>Goals</th><th>Emergency</th></tr></thead><tbody>{history.data.map((item, index) => <tr key={item.healthId ?? index}><td>{date(item.assessmentDate)}</td><td>{item.healthScore}</td><td>{item.savingsScore}</td><td>{item.spendingScore}</td><td>{item.goalScore}</td><td>{item.emergencyScore}</td></tr>)}</tbody></table></div>}<Pagination page={historyPage} meta={history.meta} change={setHistoryPage} /><small className="muted">Scores are illustrative, not credit scores. Historical records store scores, not their original calculation inputs.</small></section>
  </>;
}
