import { PublicPage } from "@/components/public-page";
import { PublicActions } from "@/components/public-layout";
import { ProductIcon } from "@/components/brand";
import { ChatPreview, GoalPreview, TransactionPreview, PlanningPreview } from "@/components/public-previews";
const steps = [
 ["profile","Create an account","Sign up with the supported name, email and password fields. Confirm your email when required, then sign in to your private workspace.","Account → Sign in → Private workspace"],
 ["transactions","Record financial activity","Add income and expenses with amounts, categories and dates. Merchant names and notes help keep entries meaningful.","Income + Expenses + Categories"],
 ["dashboard","View the dashboard","Scan recorded balance, monthly income and expenses, goal savings and cash flow. These values describe your records, not a wallet balance.","Balance · Income · Expenses · Goal savings"],
 ["analytics","Understand spending","Choose the default or custom analytics period. Review categories and monthly patterns; save insights and illustrative wellness assessments when useful.","Period → Categories → Monthly patterns"],
 ["goals","Create a savings goal","Give the goal a name, target amount and future target date. Record any already-saved amount within the target.","Goal name + Target amount + Target date"],
 ["goals","Contribute and track","Record contributions, then review saved and remaining amounts and progress. Pause/resume an active plan when your priorities change.","Saved → Remaining → Progress"],
 ["planning","Test a savings plan","Enter hypothetical income, expenses, desired saving and a horizon in the simulator. Review projected savings and goal completion estimates where available.","Monthly scenario → Timeline → Projection"],
 ["shield","Check affordability","Enter a potential purchase amount, select a goal if relevant and choose an emergency buffer. Review the assessment and its limitations before deciding.","Purchase + Recorded context → Assessment"],
 ["coach","Ask your AI financial coach","Start a conversation in English, বাংলা or Banglish. Ask about recorded spending and goals, review guidance and keep useful recommendations.","Your question → Contextual guidance → Your decision"],
];
const visuals = [null, <TransactionPreview key="transactions" />, null, null, <GoalPreview key="goal" />, null, <PlanningPreview key="plan" />, <PlanningPreview affordability key="purchase" />, <ChatPreview key="chat" />];
export default function HowItWorks(){return <PublicPage><section className="workflow-hero container"><p className="eyebrow">YOUR FIRST VISIT, EXPLAINED</p><h1>Your records. A practical path forward.</h1><p>Nine steps through the actual application. Start small, explore the context, then return to the tools as your circumstances change.</p><div className="workflow-key"><span>01 Account</span><ProductIcon name="arrow" /><span>09 AI Coach</span></div></section><div className="workflow-timeline container">{steps.map(([icon,title,text,preview],index) => <section className="workflow-step" data-workflow-step key={title}><div className="timeline-number">{String(index+1).padStart(2,"0")}</div><div className="timeline-copy"><p className="eyebrow">{index < 3 ? "BUILD YOUR CONTEXT" : index < 6 ? "UNDERSTAND & SET A TARGET" : "EXPLORE YOUR NEXT MOVE"}</p><h2>{title}</h2><p>{text}</p></div>{visuals[index] ? <div className="timeline-visual">{visuals[index]}</div> : <div className="step-preview"><ProductIcon name={icon} /><strong>{preview}</strong><small>Workflow preview · No action performed</small></div>}</section>)}</div><section className="container workflow-finish"><p className="eyebrow">A ROUTINE, NOT A ONE-TIME REPORT</p><h2 className="workflow-loop">{["Record", "Understand", "Plan", "Ask AI", "Improve"].map((label,index) => <span key={label}>{index > 0 && <i aria-hidden="true">↓</i>}{label}</span>)}</h2><p>Ready to try the workflow? Keep your context current and revisit the tools as your records grow.</p><PublicActions signupLabel="Create an account" dashboardLabel="Continue in your dashboard" /></section></PublicPage>;}
