import Link from "next/link";
import { PublicPage } from "@/components/public-page";
import { ProductPreview } from "@/components/product-preview";
import { ChatPreview, GoalPreview, TransactionPreview, PlanningPreview } from "@/components/public-previews";
import { ProductIcon } from "@/components/brand";

const features = [
  { id: "goals", role: "CORE · GOAL-BASED SAVINGS PLANNING", title: "Savings goals & planning", summary: "Understand what remains, the saving pace you need and whether a plan fits the deadline.", details: ["Create or select a goal with a target amount and date; review remaining savings and required monthly saving", "Record contributions, follow progress and pause/resume eligible goals", "Generate the Goal Details Savings Plan from recorded activity; review the monthly gap, spending budgets, projected monthly saving and deadline feasibility"], visual: <GoalPreview /> },
  { id: "affordability", role: "CORE · PURCHASE DECISION", title: "Purchase affordability", summary: "Check a planned purchase against recorded cash flow and savings commitments.", details: ["Enter a purchase amount and choose an emergency-buffer horizon", "Saved funds in all non-cancelled goals are reserved, including paused and completed goals", "Optionally select an ACTIVE goal to also check its required monthly saving pace", "Review the deterministic verdict, reserved savings, buffer, available amount and limitations; multilingual AI explanation is optional"], visual: <PlanningPreview affordability /> },
  { id: "simulator", role: "SUPPORTING · HYPOTHETICAL SAVINGS SCENARIO", title: "Savings simulator", summary: "Explore how a different monthly scenario could affect savings and timing.", details: ["Enter hypothetical monthly income, expenses and desired savings", "Choose a time horizon and optionally select a goal", "Review projected savings and goal completion estimates where possible; no records change", "This What-if Simulator uses your scenario inputs, separately from the recorded-data Goal Details Savings Plan"], visual: <PlanningPreview /> },
  { id: "transactions", role: "SUPPORTING · RECORDED INPUTS", title: "Transaction management", summary: "Keep the activity behind a savings plan or purchase check current.", details: ["Manually record MFS-style cash in, cash out, merchant payments and recharge in BDT", "Add, edit and delete entries; include category, merchant or note details", "Search and filter your history; no automatic wallet synchronization or payment execution"], visual: <TransactionPreview /> },
  { id: "dashboard", role: "SUPPORTING · FINANCIAL CONTEXT", title: "Financial dashboard", summary: "Review your recorded position before using the decision tools.", details: ["Recorded cash-flow balance; not a live wallet balance", "Monthly income, expenses, goal savings and recent transactions", "Cash-flow visualization and stored insights support review; the saved wellness assessment is a secondary, illustrative view"], visual: <ProductPreview /> },
  { id: "analytics", role: "SUPPORTING · SPENDING CONTEXT", title: "Financial analytics", summary: "Understand the spending patterns behind your savings assumptions.", details: ["Review recorded income, expenses and net cash flow by period", "Explore category spending and monthly trends", "Refresh and save insights; illustrative wellness assessments and their history remain secondary tools"], visual: <div className="mini-product"><p className="eyebrow">MONTHLY TRENDS · STATIC EXAMPLE</p><div className="catalog-chart" aria-label="Illustrative monthly pattern, not account data">{[45,65,55,80,70,90].map((height,index) => <span key={index} style={{height:`${height}%`}} />)}</div><div className="row"><span>Income</span><span>Expenses</span><span>Net cash flow</span></div><p className="muted">Compare patterns within your selected period.</p></div> },
  { id: "ai-coach", role: "SUPPORTING · OPTIONAL MULTILINGUAL GUIDANCE", title: "AI financial coach", summary: "Discuss recorded context in the language you prefer.", details: ["Ask about recorded spending and an optional selected savings goal", "English, বাংলা and Latin-script Banglish", "Keep conversation history and review generated recommendations", "AI provides illustrative guidance and can make mistakes; backend calculations determine plans and affordability verdicts, and no transactions are executed"], visual: <ChatPreview /> },
  { id: "workspace", role: "SUPPORTING · ACCOUNT ACCESS", title: "Account & workspace", summary: "Authenticated access keeps your recorded context specific to your account.", details: ["Protected financial pages and user-isolated records", "Profile updates and language preferences are secondary account housekeeping", "Email and sessions are managed through Supabase Auth"], visual: <div className="mini-product workspace-preview"><span className="profile-avatar" aria-hidden="true">D</span><h3>Your private workspace</h3><p>Profile · Language preference · Recorded activity</p><div className="language-tags"><span>English</span><span lang="bn">বাংলা</span><span>Banglish</span></div><small>Illustrative account presentation</small></div> },
];

export default function Features() {
  return <PublicPage>
    <section className="catalog-hero container">
      <p className="eyebrow">TWO DECISIONS. RECORDED CONTEXT.</p>
      <h1>Plan a savings goal.<br />Assess a purchase.</h1>
      <p>The core tools support two customer decisions. Recorded transactions, dashboard and spending context, a hypothetical simulator and optional multilingual guidance support the process.</p>
      <nav className="catalog-index" aria-label="Feature catalog">{features.map((feature,index) => <Link key={feature.id} href={`#${feature.id}`}><span>0{index+1}</span>{feature.title}</Link>)}</nav>
    </section>
    <div className="feature-catalog container">{features.map((feature,index) => <section data-feature={feature.id} id={feature.id} className={`catalog-row ${index%2 ? "reverse" : ""}`} key={feature.id}><div className="catalog-copy"><p className="eyebrow">{feature.role}</p><h2>{feature.title}</h2><p>{feature.summary}</p><ul>{feature.details.map(detail => <li key={detail}>{detail}</li>)}</ul></div><div className="catalog-visual">{feature.visual}</div></section>)}</div>
    <section className="container contextual-cta"><div><p className="eyebrow">CHOOSE YOUR JOURNEY</p><h2>From recorded activity to a goal plan or purchase check.</h2></div><Link className="button" href="/how-it-works">Follow the two journeys <ProductIcon name="arrow" /></Link></section>
  </PublicPage>;
}
