import Link from "next/link";
import { PublicPage } from "@/components/public-page";
import { ProductPreview } from "@/components/product-preview";
import { ChatPreview, GoalPreview, TransactionPreview, PlanningPreview } from "@/components/public-previews";
import { ProductIcon } from "@/components/brand";
const features = [
 { id:"dashboard", title:"Financial dashboard", summary:"Start with the financial picture behind your records.", details:["Recorded cash-flow balance; not a live wallet balance","Monthly income, expenses and goal savings","Cash-flow visualization, recent transactions and saved wellness assessment"], visual:<ProductPreview /> },
 { id:"transactions", title:"Transaction management", summary:"Keep the everyday details useful and organized.", details:["Add, edit and delete recorded income and expenses","Categorize entries and include merchant or note details","Search and filter your history; no automatic wallet synchronization"], visual:<TransactionPreview /> },
 { id:"goals", title:"Savings goals", summary:"A clear target with progress you can follow.", details:["Choose a goal name, target amount and future date","Record contributions; review saved, remaining and progress values","Pause/resume a goal and view its savings plan"], visual:<GoalPreview /> },
 { id:"analytics", title:"Financial analytics", summary:"Move from individual entries to spending patterns.", details:["Review recorded income, expenses and net cash flow by period","Explore category spending and monthly trends","Refresh and save insights; save illustrative wellness assessments and view history"], visual:<div className="mini-product"><p className="eyebrow">MONTHLY TRENDS · STATIC EXAMPLE</p><div className="catalog-chart" aria-label="Illustrative monthly pattern, not account data">{[45,65,55,80,70,90].map((height,index) => <span key={index} style={{height:`${height}%`}} />)}</div><div className="row"><span>Income</span><span>Expenses</span><span>Net cash flow</span></div><p className="muted">Compare patterns within your selected period.</p></div> },
 { id:"ai-coach", title:"AI financial coach", summary:"A conversation grounded in recorded context.", details:["Discuss your recorded finances and selected savings goal","English, বাংলা and Latin-script Banglish","Keep conversation history and review generated recommendations","Illustrative guidance: AI can make mistakes and does not execute transactions"], visual:<ChatPreview /> },
 { id:"simulator", title:"Savings simulator", summary:"Try a scenario before changing your plans.", details:["Enter hypothetical monthly income, expenses and desired savings","Choose a time horizon and optionally select a goal","Review projected savings and goal completion estimates where possible; no records change"], visual:<PlanningPreview /> },
 { id:"affordability", title:"Affordability assessment", summary:"Consider a purchase alongside your other commitments.", details:["Enter a purchase amount and emergency-buffer horizon","Assess recorded cash flow and reserved goal savings","Review the decision and limitations; optionally request an AI explanation"], visual:<PlanningPreview affordability /> },
 { id:"workspace", title:"Personal workspace", summary:"Your account is the home for your financial context.", details:["Authenticated, protected financial pages","Update supported profile information and language preference","Email and sessions are managed through Supabase Auth"], visual:<div className="mini-product workspace-preview"><span className="profile-avatar" aria-hidden="true">D</span><h3>Your private workspace</h3><p>Profile · Language preference · Recorded activity</p><div className="language-tags"><span>English</span><span lang="bn">বাংলা</span><span>Banglish</span></div><small>Illustrative account presentation</small></div> },
];
export default function Features() { return <PublicPage><section className="catalog-hero container"><p className="eyebrow">8 CAPABILITIES. ONE WORKSPACE.</p><h1>More clarity. More ways to plan.</h1><p>What can you actually do? Explore the tools already available in the application.</p><nav className="catalog-index" aria-label="Feature catalog">{features.map((feature,index) => <Link key={feature.id} href={`#${feature.id}`}><span>0{index+1}</span>{feature.title}</Link>)}</nav></section><div className="feature-catalog container">{features.map((feature,index) => <section data-feature={feature.id} id={feature.id} className={`catalog-row ${index%2 ? "reverse" : ""}`} key={feature.id}><div className="catalog-copy"><p className="eyebrow">CAPABILITY 0{index+1}</p><h2>{feature.title}</h2><p>{feature.summary}</p><ul>{feature.details.map(detail => <li key={detail}>{detail}</li>)}</ul></div><div className="catalog-visual">{feature.visual}</div></section>)}</div><section className="container contextual-cta"><div><p className="eyebrow">CONNECT THE TOOLS</p><h2>See how everything works together.</h2></div><Link className="button" href="/how-it-works">Follow the product journey <ProductIcon name="arrow" /></Link></section></PublicPage>; }
