import Link from "next/link";
import { PublicPage } from "@/components/public-page";
import { PublicActions } from "@/components/public-layout";
import { ProductIcon } from "@/components/brand";
export default function Security(){return <PublicPage><section className="security-hero"><div className="container feature-split"><div><p className="eyebrow">CLEAR ACCESS. CLEAR BOUNDARIES.</p><h1>Your financial records belong to you.</h1><p>Understand how this prototype handles private account access, recorded information and AI context.</p></div><div className="trust-diagram"><ProductIcon name="shield" /><strong>Authentication</strong><span>↓</span><strong>Ownership checks</strong><span>↓</span><strong>Your recorded workspace</strong></div></div></section>
 <div className="container security-content">
 <section data-security-section className="security-row"><span>01</span><div><h2>Secure authentication</h2><p>Supabase Auth manages sign-in, sessions and email confirmation. The application uses the existing authenticated session to access protected APIs.</p></div><ProductIcon name="profile" /></section>
 <section data-security-section className="security-row"><span>02</span><div><h2>Protected workspace</h2><p>Private pages require an authenticated session. API endpoints verify authentication before accessing financial records.</p><div className="boundary-path"><span>Public website</span><span>→ Sign in →</span><strong>Private workspace</strong></div></div><ProductIcon name="shield" /></section>
 <section data-security-section className="security-row"><span>03</span><div><h2>User-isolated records</h2><p>Ownership checks restrict account records to their owner. Changing a transaction, goal or conversation ID does not grant access to another user’s records.</p></div><ProductIcon name="dashboard" /></section>
 <section data-security-section className="security-row"><span>04</span><div><h2>Private financial records</h2><p>Transactions, goals, profile information and conversation history live in your authenticated workspace. The public site uses static examples and does not request your financial data.</p></div><ProductIcon name="transactions" /></section>
 <section data-security-section className="ai-boundary"><div><p className="eyebrow">05 · AI DATA BOUNDARIES</p><h2>Useful context, with a clear purpose.</h2><p>The coach receives a minimized recorded-data summary and recent messages relevant to the conversation. Do not include passwords, card details or private identifiers.</p></div><div className="boundary-note"><strong>Recorded context + recent messages</strong><ProductIcon name="arrow" /><strong>Illustrative AI guidance</strong><small>AI can make mistakes. Review its output before acting.</small></div></section>
 <section data-security-section className="wallet-boundary"><p className="eyebrow">06 · RECORDED DATA VS LIVE WALLET</p><h2>A record is not a wallet connection.</h2><div className="boundary-columns"><div><h3>This prototype does</h3><ul><li>Record financial information</li><li>Analyze recorded cash flow</li><li>Track savings goals</li><li>Simulate scenarios</li><li>Provide AI-assisted guidance</li></ul></div><div><h3>This prototype does not</h3><ul><li>Access a live Upay wallet</li><li>Move money</li><li>Execute purchases</li><li>Verify real wallet balances</li><li>Guarantee financial outcomes</li></ul></div></div></section>
 <section data-security-section className="security-finish"><p className="eyebrow">07 · RESPONSIBLE PROTOTYPE USE</p><h2>Understand the prototype, then get started.</h2><p>AI guidance is contextual and illustrative, not guaranteed professional financial advice. This hackathon project does not claim official Upay infrastructure, regulatory approval or security certification.</p><PublicActions signupLabel="Create an account" dashboardLabel="Return to your dashboard" /><Link className="inline-link section-space" href="/about">Read the product story <ProductIcon name="arrow" /></Link></section>
 </div></PublicPage>;}
